before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: hzU5/KBiTv7OVmSdT6X+b142M9Ro1vRyse4V8YCwPGNUnTWhaHPTxIgrhuqNscD9m2oZIe1ZPB06oTZ6hU5P3V4TDWhqY+ncjueKH1fcC/FAMLNryFRck3g8KpZuCwxwHmk6uSnMLCt1XH4VKDLvq0YXzNRfkt5gPZinWocXGKOPLQxKTdAyqXTipQDpl7AwWEX2PcxHg2DlAOvfUl2+hrEyK/SGlh8IsC6nki7Xbufx25AKkMo4vWkRoMgM0plG0km9oHLtJQSK1IqqGcuuoqse0bd6t7ldbC494nYp0ZyqF/8UvkesK7mF6U6hSDzVB0B/E7yI9400ZlizyFE1d26cb6KwYGh+UFiu9Cdl8CwqEpNwbKRYJmHST5hpC5lvrzMBsb9JaNcre1pp3fouJ6GO9bn4a+JTM2H2m6zHUKSYKsbYSEG5Qn8UHmtp4S5tIuAC0Q2qEF8+UzJwAy6OcA292DwpECIsZaQxhzRao8OoK2KK86i4TuMSkAoq68uL8oqz00lM5+4PojqEPC6X8nIPhDsEErUU2xUZZnpz7vr1lH3MKNJsWP0AU0J0l3A3jQvn3ZyO9NXTd1Yt51D6m4f3usQAap0WYuTaEf8RjS+kbuyCcvotMjOGhc6mscGW0bx3IpTKH+o4Cl+fqmQdE7ek8PRPh37fl39mMzvAdo4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
